### ISSUE TITLE
ch.bfe.solarenergie-eignung-daecher feature API slow -> missing indices ?

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-chsdi3#3612]
"I've noticed some really slow response times in the last few days when using the `identify` endpoint for the ch.bfe.solarenergie-eignung-daecher layer and the `limit` keyword set, e.g.

https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry=501048.564,113869.963&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=653,644,96&layers=all:ch.bfe.solarenergie-eignung-daecher&mapExtent=501019.227,113837.867,501087.963,113903.229&returnGeometry=True&sr=21781&limit=10&tolerance=1

This call now takes around 4 - 10 seconds to return, it used to be a few ms. If I omit the `limit` keyword, we're down to around ~1s.

"
according https://groups.google.com/d/msgid/geoadmin-api/76d80df9-913d-4075-b0cd-dbaaad9a815an%40googlegroups.com

**Comment by davidoesch** [comment]
related to https://github.com/geoadmin/mf-chsdi3/issues/3607 ?

**Comment by ltclm** [comment]
the query on old db infra was faster:

```sql
EXPLAIN ANALYZE SELECT *
    FROM bfe.view_solarenergie_daecher_gs
    WHERE ST_DWithin(bfe.view_solarenergie_daecher_gs.the_geom, ST_Transform(ST_GeomFromWKB('\x01010000004c378941e2941e4121b07268dfccfb40'::bytea, 21781), 2056), 0.10526186830011534)
    LIMIT 10


-- pg9
"Limit  (cost=36527.21..36536.16 rows=1 width=677) (actual time=804.537..804.539 rows=1 loops=1)"
"  ->  GroupAggregate  (cost=36527.21..36536.15 rows=1 width=393) (actual time=804.535..804.536 rows=1 loops=1)"
"        Group Key: d.df_uid"
"        ->  Sort  (cost=36527.21..36527.50 rows=116 width=393) (actual time=804.400..804.408 rows=12 loops=1)"
"              Sort Key: d.df_uid"
"              Sort Method: quicksort  Memory: 31kB"
"              ->  Nested Loop  (cost=2795.07..36523.23 rows=116 width=393) (actual time=14.499..804.365 rows=12 loops=1)"
"                    Join Filter: (f.monat = mv.monat)"
"                    Rows Removed by Join Filter: 132"
"                    ->  Hash Join  (cost=2794.51..31717.34 rows=113 width=349) (actual time=14.470..804.065 rows=12 loops=1)"
"                          Hash Cond: ((vd.col = r.col) AND (vd.""row"" = r.""row"") AND (((date_part('month'::text, solarenergie_raster_files_sisdir.date))::integer) = f.monat))"
"                          ->  Nested Loop  (cost=0.57..25455.60 rows=308149 width=16) (actual time=0.030..603.071 rows=297876 loops=1)"
"                                ->  Limit  (cost=0.14..1.88 rows=12 width=10) (actual time=0.014..0.053 rows=12 loops=1)"
"                                      ->  Index Scan Backward using solarenergie_raster_files_sisdir_date on solarenergie_raster_files_sisdir  (cost=0.14..17.54 rows=120 width=10) (actual time=0.012..0.038 rows=12 loops=1)"
"                                ->  Index Scan using solarenergie_raster_values_fk_raster_files_sisdir on solarenergie_raster_values_sisdir vd  (cost=0.43..1864.34 rows=25679 width=14) (actual time=0.009..18.696 rows=24823 loops=12)"
"                                      Index Cond: (fk_raster_files = solarenergie_raster_files_sisdir.pk_raster_files)"
"                          ->  Hash  (cost=2792.03..2792.03 rows=109 width=345) (actual time=0.883..0.883 rows=12 loops=1)"
"                                Buckets: 1024  Batches: 1  Memory Usage: 6kB"
"                                ->  Hash Join  (cost=11.50..2792.03 rows=109 width=345) (actual time=0.397..0.865 rows=12 loops=1)"
"                                      Hash Cond: (v.fk_raster_files = f.pk_raster_files)"
"                                      ->  Nested Loop  (cost=9.35..2785.18 rows=960 width=335) (actual time=0.330..0.714 rows=120 loops=1)"
"                                            ->  Nested Loop  (cost=4.71..21.18 rows=8 width=321) (actual time=0.284..0.305 rows=1 loops=1)"
"                                                  ->  Index Scan using solarenergie_daecher_the_geom_1447239458210 on solarenergie_daecher d  (cost=0.42..8.69 rows=1 width=317) (actual time=0.038..0.057 rows=1 loops=1)"
"                                                        Index Cond: (the_geom && '010300002008080000010000000500000004A72BF6DB1443415FAF53160EFF304104A72BF6DB1443419391384C0EFF30411E181E11DC1443419391384C0EFF30411E181E11DC1443415FAF53160EFF304104A72BF6DB1443415FAF53160EFF3041'::geometry)"
"                                                        Filter: (('01010000200808000091DFA403DC144341792046310EFF3041'::geometry && st_expand(the_geom, 0.105261868300115::double precision)) AND _st_dwithin(the_geom, '01010000200808000091DFA403DC144341792046310EFF3041'::geometry, 0.105261868300115::double precision))"
"                                                        Rows Removed by Filter: 1"
"                                                  ->  Bitmap Heap Scan on solarenergie_raster r  (cost=4.30..12.48 rows=1 width=132) (actual time=0.242..0.243 rows=1 loops=1)"
"                                                        Recheck Cond: (st_centroid(d.the_geom) && the_geom)"
"                                                        Filter: _st_intersects(st_centroid(d.the_geom), the_geom)"
"                                                        Heap Blocks: exact=1"
"                                                        ->  Bitmap Index Scan on solarenergie_raster_the_geom  (cost=0.00..4.29 rows=2 width=0) (actual time=0.191..0.191 rows=1 loops=1)"
"                                                              Index Cond: (st_centroid(d.the_geom) && the_geom)"
"                                            ->  Bitmap Heap Scan on solarenergie_raster_values_sis v  (cost=4.63..344.30 rows=120 width=14) (actual time=0.042..0.250 rows=120 loops=1)"
"                                                  Recheck Cond: ((""row"" = r.""row"") AND (col = r.col))"
"                                                  Heap Blocks: exact=120"
"                                                  ->  Bitmap Index Scan on solarenergie_raster_values_sis_sort  (cost=0.00..4.60 rows=120 width=0) (actual time=0.027..0.027 rows=120 loops=1)"
"                                                        Index Cond: ((""row"" = r.""row"") AND (col = r.col))"
"                                      ->  Hash  (cost=2.00..2.00 rows=12 width=14) (actual time=0.062..0.062 rows=12 loops=1)"
"                                            Buckets: 1024  Batches: 1  Memory Usage: 1kB"
"                                            ->  Subquery Scan on f  (cost=0.14..2.00 rows=12 width=14) (actual time=0.009..0.048 rows=12 loops=1)"
"                                                  ->  Limit  (cost=0.14..1.88 rows=12 width=10) (actual time=0.008..0.032 rows=12 loops=1)"
"                                                        ->  Index Scan Backward using solarenergie_raster_files_sis_date on solarenergie_raster_files_sis  (cost=0.14..17.54 rows=120 width=10) (actual time=0.006..0.018 rows=12 loops=1)"
"                    ->  Index Scan using solarenergie_daecher_mvalues_df_uid on solarenergie_daecher_mvalues mv  (cost=0.57..34.47 rows=645 width=60) (actual time=0.005..0.014 rows=12 loops=12)"
"                          Index Cond: (df_uid = d.df_uid)"
"        SubPlan 1"
"          ->  Seq Scan on solarenergie_daecher_klasse k  (cost=0.00..1.07 rows=1 width=42) (actual time=0.004..0.005 rows=1 loops=1)"
"                Filter: (klasse = d.klasse)"
"                Rows Removed by Filter: 5"
"Planning time: 8.209 ms"
"Execution time: 804.760 ms"



-- pg12

"Limit  (cost=357087.87..410123.74 rows=10 width=676) (actual time=6855.266..6855.276 rows=1 loops=1)"
"  ->  GroupAggregate  (cost=357087.87..5602325.90 rows=989 width=676) (actual time=6855.265..6855.274 rows=1 loops=1)"
"        Group Key: d.df_uid"
"        ->  Merge Join  (cost=357087.87..5582119.67 rows=293976 width=392) (actual time=6855.119..6855.172 rows=12 loops=1)"
"              Merge Cond: (mv.df_uid = d.df_uid)"
"              Join Filter: (((date_part('month'::text, solarenergie_raster_files_sis.date))::integer) = mv.monat)"
"              Rows Removed by Join Filter: 132"
"              ->  Index Scan using solarenergie_daecher_mvalues_df_uid on solarenergie_daecher_mvalues mv  (cost=0.57..4909201.85 rows=118694352 width=60) (actual time=0.014..4307.399 rows=33180241 loops=1)"
"              ->  Materialize  (cost=313859.08..315328.47 rows=293877 width=348) (actual time=466.141..466.160 rows=133 loops=1)"
"                    ->  Sort  (cost=313859.08..314593.77 rows=293877 width=348) (actual time=466.138..466.148 rows=12 loops=1)"
"                          Sort Key: d.df_uid"
"                          Sort Method: quicksort  Memory: 31kB"
"                          ->  Merge Join  (cost=177705.85..192744.92 rows=293877 width=348) (actual time=466.108..466.135 rows=12 loops=1)"
"                                Merge Cond: ((r.col = v.col) AND (r.""row"" = v.""row""))"
"                                ->  Sort  (cost=66216.64..66278.02 rows=24550 width=320) (actual time=0.202..0.205 rows=1 loops=1)"
"                                      Sort Key: r.col, r.""row"""
"                                      Sort Method: quicksort  Memory: 25kB"
"                                      ->  Nested Loop  (cost=3.44..60818.03 rows=24550 width=320) (actual time=0.145..0.199 rows=1 loops=1)"
"                                            ->  Index Scan using solarenergie_daecher_the_geom_1447239458210 on solarenergie_daecher d  (cost=0.67..33.68 rows=989 width=316) (actual time=0.049..0.064 rows=1 loops=1)"
"                                                  Index Cond: (the_geom && st_expand('010100002008080000EA263148DC144341062B87F60DFF3041'::geometry, '0.10526186830011534'::double precision))"
"                                                  Filter: st_dwithin(the_geom, '010100002008080000EA263148DC144341062B87F60DFF3041'::geometry, '0.10526186830011534'::double precision)"
"                                                  Rows Removed by Filter: 1"
"                                            ->  Index Scan using solarenergie_raster_the_geom on solarenergie_raster r  (cost=2.78..61.44 rows=2 width=132) (actual time=0.061..0.098 rows=1 loops=1)"
"                                                  Index Cond: (the_geom && st_centroid(d.the_geom))"
"                                                  Filter: st_intersects(st_centroid(d.the_geom), the_geom)"
"                                ->  Materialize  (cost=111488.12..121912.90 rows=297858 width=40) (actual time=434.044..463.361 rows=25717 loops=1)"
"                                      ->  Merge Join  (cost=111488.12..121168.25 rows=297858 width=40) (actual time=434.040..456.620 rows=25717 loops=1)"
"                                            Merge Cond: ((vd.col = v.col) AND (vd.""row"" = v.""row"") AND (((date_part('month'::text, solarenergie_raster_files_sisdir.date))::integer) = ((date_part('month'::text, solarenergie_raster_files_sis.date))::integer)))"
"                                            ->  Sort  (cost=55234.66..55979.35 rows=297876 width=16) (actual time=214.076..218.401 rows=25717 loops=1)"
"                                                  Sort Key: vd.col, vd.""row"", ((date_part('month'::text, solarenergie_raster_files_sisdir.date))::integer)"
"                                                  Sort Method: external merge  Disk: 7600kB"
"                                                  ->  Nested Loop  (cost=0.57..23058.75 rows=297876 width=16) (actual time=0.026..77.544 rows=297876 loops=1)"
"                                                        ->  Limit  (cost=0.14..1.88 rows=12 width=14) (actual time=0.010..0.071 rows=12 loops=1)"
"                                                              ->  Index Scan Backward using solarenergie_raster_files_sisdir_date on solarenergie_raster_files_sisdir  (cost=0.14..17.54 rows=120 width=14) (actual time=0.009..0.062 rows=12 loops=1)"
"                                                        ->  Index Scan using solarenergie_raster_values_fk_raster_files_sisdir on solarenergie_raster_values_sisdir vd  (cost=0.43..1673.17 rows=24823 width=14) (actual time=0.010..3.823 rows=24823 loops=12)"
"                                                              Index Cond: (fk_raster_files = solarenergie_raster_files_sisdir.pk_raster_files)"
"                                            ->  Materialize  (cost=56253.16..57742.54 rows=297876 width=24) (actual time=219.955..227.818 rows=25717 loops=1)"
"                                                  ->  Sort  (cost=56253.16..56997.85 rows=297876 width=24) (actual time=219.952..224.907 rows=25717 loops=1)"
"                                                        Sort Key: v.col, v.""row"", ((date_part('month'::text, solarenergie_raster_files_sis.date))::integer)"
"                                                        Sort Method: external merge  Disk: 11096kB"
"                                                        ->  Nested Loop  (cost=0.57..23058.75 rows=297876 width=24) (actual time=0.039..78.986 rows=297876 loops=1)"
"                                                              ->  Limit  (cost=0.14..1.88 rows=12 width=14) (actual time=0.019..0.084 rows=12 loops=1)"
"                                                                    ->  Index Scan Backward using solarenergie_raster_files_sis_date on solarenergie_raster_files_sis  (cost=0.14..17.54 rows=120 width=14) (actual time=0.018..0.075 rows=12 loops=1)"
"                                                              ->  Index Scan using solarenergie_raster_values_sis_fk_raster_files on solarenergie_raster_values_sis v  (cost=0.43..1673.17 rows=24823 width=14) (actual time=0.010..3.833 rows=24823 loops=12)"
"                                                                    Index Cond: (fk_raster_files = solarenergie_raster_files_sis.pk_raster_files)"
"        SubPlan 1"
"          ->  Seq Scan on solarenergie_daecher_klasse k  (cost=0.00..1.07 rows=1 width=42) (actual time=0.011..0.011 rows=1 loops=1)"
"                Filter: (klasse = d.klasse)"
"                Rows Removed by Filter: 5"
"Planning Time: 10.259 ms"
"Execution Time: 6858.210 ms"
```
@davidoesch i will have a deeper look into it as soon as i find some time. please open jira tickets :-)

**Comment by ltclm** [comment]
We were able to improve the index behind the query. 
```
EXPLAIN (BUFFERS, ANALYZE) SELECT *
    FROM bfe.view_solarenergie_daecher_gs
    WHERE ST_DWithin(bfe.view_solarenergie_daecher_gs.the_geom, ST_Transform(ST_GeomFromWKB('\x01010000004c378941e2941e4121b07268dfccfb40'::bytea, 21781), 2056), 0.10526186830011534)
    LIMIT 10

-- Execution Time: 7497.961 ms
CREATE INDEX solarenergie_daecher_mvalues_df_uid
    ON bfe.solarenergie_daecher_mvalues USING btree
    (df_uid ASC NULLS LAST)
    TABLESPACE pg_default;

-- Execution Time: 444.296 ms
CREATE INDEX solarenergie_daecher_mvalues_df_uid
    ON bfe.solarenergie_daecher_mvalues USING btree
    (df_uid DESC NULLS LAST)
    TABLESPACE pg_default;
```

The server-side response time is now less than 500ms with and without limit parameter.

**Comment by davidoesch** [comment]
Imho solved now

**Comment by davidoesch** [comment]
I could reproduce this. Marcel?  Do I do sth wrong?

> However, I'm wondering whether there's an index missing in the DB, if I query
> 
> https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometry=501048.564,113869.963&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=653,644,96&layers=all:ch.bfe.solarenergie-eignung-daecher&mapExtent=501019.227,113837.867,501087.963,113903.229&returnGeometry=True&sr=21781&limit=1&tolerance=1
> 
> with an arbitrary point as geometry parameter, the first call takes anywhere between 5s - Guru meditation. All subsequent calls for the exact same point take around 15ms. If you change the point slightly (even increase or decrease one single digit after the decimal point), the call again takes > 5s. Subsequent calls then again again take ~15ms. I'm testing this with Postman, so I don't expect local caching to be the source of this weird behaviour. I also tested it across several browsers, i.e. make the first call on browser A, wait 5s until it returns. Do calls 2-n on browser B, admire the 15ms.
>

**Comment by ltclm** [comment]
there seems to be an issue with the postgres performance when using this identify service with the parameter
``limit=1``.
I dont have yet figured out how to fix this on the database level. There are some discussions about poor performance with LIMIT=1 Queries [1].
As short-term advice i propose to not use the service with limit=1 anymore, use limit=10 or no limit parameter instead.

[1] https://stackoverflow.com/questions/21385555/postgresql-query-very-slow-with-limit-1/27237698

**Comment by cype** [comment]
Please reopen this issue! The problem is not solved. The short term adivce (12 Feb) ist now a long term adivce ?

Sonnendach.ch ist still slow because of this and clients who use the API complain about the poor performance of the API-Calls...

**Comment by cype** [comment]
update: client even says "he will abandon our API if this is not resolved quickly"...

**Comment by davidoesch** [comment]
Jira Ticket
https://jira.swisstopo.ch/browse/BGDIINF_SB-1813

**Comment by rebert** [comment]
@davidoesch @cype we are going to update this layer soon. While doing so, we will take extra care about the indices...

**Comment by davidoesch** [comment]
fixed on 2.6
